#ifndef NOTTOOBRIGHT_VERSION_H
#define NOTTOOBRIGHT_VERSION_H

#define APP_VERSION_MAJOR 0
#define APP_VERSION_MINOR 0
#define APP_VERSION_PATCH 33
#define APP_VERSION_BUILD 0

#define APP_DISPLAY_NAME_STRING "Not Too Bright"
#define APP_DISPLAY_NAME_WSTRING L"Not Too Bright"

#define APP_VERSION_RESOURCE 0,0,33,0
#define APP_VERSION_STRING "0.0.33"
#define APP_FILE_VERSION_STRING "0.0.33.0"
#define APP_VERSION_WSTRING L"0.0.33"

#endif
